apiVersion: v1
kind: Service
metadata:
  name: caddy-demo
  labels:
    name: caddy-demo-service
spec:
  type: NodePort
  ports:
    - port: 2015
      targetPort: 2015
      name: http
  selector:
    name: caddy-demo